version: 2
snapshot:
  enable-javascript: true
  widths: [375, 768, 1920]
discovery:
  allowed-hostnames: 
  - unified-catalog:8001
  launch-options:
    args: 
    - '--disable-gpu'
    - '--disable-dev-shm-usage'
    - '--disable-setuid-sandbox'
    - '--no-sandbox'
